import { z } from "zod";

// A lead sheet: the harmonic + melodic skeleton of the song, generated by a
// text model from the same prompt/tags that drive audio generation. Lyria
// returns audio only, so this is an independent interpretation of the brief
// rather than a transcription of the generated track.
export const leadSheetSectionSchema = z.object({
  name: z.string().min(1).max(40),
  /** One chord symbol per bar, in order. e.g. ["C", "G", "Am", "F"]. */
  chords: z.array(z.string().min(1).max(12)).min(1).max(32),
});

export const leadSheetSchema = z.object({
  title: z.string().min(1).max(120),
  keyName: z.string().min(1).max(40), // "C major", "A minor", "E Dorian"
  tempo: z.number().int().min(30).max(260),
  timeSignature: z.string().regex(/^\d{1,2}\/\d{1,2}$/),
  /** Suggested guitar capo position, 0 = none. */
  capo: z.number().int().min(0).max(9).nullable().default(0),
  sections: z.array(leadSheetSectionSchema).min(1).max(12),
  /** Full lead sheet in ABC notation — melody with chord symbols. */
  abc: z.string().min(20).max(20000),
  /** One or two sentences on how to play it (feel, strumming, voicing). */
  performanceNotes: z.string().max(600).default(""),
});

export type LeadSheetSection = z.infer<typeof leadSheetSectionSchema>;
export type LeadSheet = z.infer<typeof leadSheetSchema>;

/** Every distinct chord symbol used across the sections, in first-seen order. */
export function uniqueChords(sheet: LeadSheet): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const section of sheet.sections) {
    for (const chord of section.chords) {
      const trimmed = chord.trim();
      if (trimmed && !seen.has(trimmed)) {
        seen.add(trimmed);
        out.push(trimmed);
      }
    }
  }
  return out;
}
